// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs1M4wU5g9t7nMtG-FthMcXyMpDEZUSIA',
    appId: '1:732385870445:web:ec639eb7b327c4f0953564',
    messagingSenderId: '732385870445',
    projectId: 'flash-chat-4f618',
    authDomain: 'flash-chat-4f618.firebaseapp.com',
    storageBucket: 'flash-chat-4f618.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFam0fR1l2m3QjyVZh_fn_B9eTO3s7eAI',
    appId: '1:732385870445:android:be76ec05e58457d9953564',
    messagingSenderId: '732385870445',
    projectId: 'flash-chat-4f618',
    storageBucket: 'flash-chat-4f618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJB3bZptEdu_GHjmsHwWsr9Qf62hES4c',
    appId: '1:732385870445:ios:ed606e1d3c4c33b2953564',
    messagingSenderId: '732385870445',
    projectId: 'flash-chat-4f618',
    storageBucket: 'flash-chat-4f618.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJB3bZptEdu_GHjmsHwWsr9Qf62hES4c',
    appId: '1:732385870445:ios:ed606e1d3c4c33b2953564',
    messagingSenderId: '732385870445',
    projectId: 'flash-chat-4f618',
    storageBucket: 'flash-chat-4f618.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs1M4wU5g9t7nMtG-FthMcXyMpDEZUSIA',
    appId: '1:732385870445:web:325a1bc32cb31e19953564',
    messagingSenderId: '732385870445',
    projectId: 'flash-chat-4f618',
    authDomain: 'flash-chat-4f618.firebaseapp.com',
    storageBucket: 'flash-chat-4f618.firebasestorage.app',
  );

}